apiVersion: v1
kind: Service
metadata:
  name: samplewebapiproject
  labels:
    app: samplewebapiproject
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: samplewebapiproject

----
# this is the yaml file for deployment   


apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: samplewebapiproject
  namespace: default
  labels:
    app: samplewebapiproject
spec:
  replicas: 1
  selector:
    matchLabels:
        app: samplewebapiproject
  template:
    metadata:
      name: samplewebapiproject
      labels:
        app: samplewebapiproject
    spec:
      containers:
      - name: samplewebapiproject
        image: 
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler